name: ESP32 ULAB_LVGL_SPIRAM_PWM

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build_idf402:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Initialize micropython-ulab submodule
      run: git submodule update --init --recursive micropython-ulab
    - name: Initialize micropython-ulab submodule
      run: git submodule update --init --recursive UartRemote
    - name: Initialize lv_micropython submodule
      run: git submodule update --init --recursive 
      working-directory: lv_micropython 
    - name: Initialize lv_bindings submodule
      run: git submodule update --init --recursive lib/lv_bindings
      working-directory: lv_micropython 
    - name: Patch files
      run: |
        cp -a tools lv_micropython
        cp -a ports lv_micropython
        cp UartRemote/MicroPython/uartremote.py lv_micropython/ports/esp32/modules
        tail -n 10 lv_micropython/ports/esp32/modules/uartremote.py
        cp -a lib lv_micropython 
        cp tools/machine_pwm_1v.19.1.c lv_micropython/ports/esp32/machine_pwm.c
    - name: Install packages
      run: source tools/ci.sh && ci_esp32_idf402_setup
      working-directory: lv_micropython 
    - name: Build
      run: source tools/ci.sh && ci_esp32_build
      working-directory: lv_micropython 
    - run: |
        export TIMESTAMP=`date +%Y%m%d-%H%M`
        export FIRMWARE=firmware_ESP32_ULAB_LVGL_SPIRAM_PWM_$TIMESTAMP.bin
        cp lv_micropython/ports/esp32/build-GENERIC_ULAB_LVGL_SPIRAM/firmware.bin build/$FIRMWARE
        git config --global user.name 'Ste7an'
        git config --global user.email 'ste7anste7an@users.noreply.github.com'
        git add build
        git diff --exit-code || git commit -m "compiled by GitHub Action"
        git push
    - uses: actions/upload-artifact@v2
      with:
        name: firmware_GENERIC_ULAB_LVGL_SPIRAM.bin
        path: lv_micropython/ports/esp32/build-GENERIC_ULAB_LVGL_SPIRAM/firmware.bin
